# Build Stage
FROM golang:1.25-alpine AS builder

WORKDIR /src
COPY pkg ./pkg

WORKDIR /src/api-gateway
COPY api-gateway/go.mod api-gateway/go.sum ./
RUN go mod download

COPY api-gateway .

RUN CGO_ENABLED=0 GOOS=linux go build -o api-gateway ./cmd/main.go


# Run Stage
FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /src/api-gateway/api-gateway .

EXPOSE 8080

CMD ["./api-gateway"]