# Build Stage
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY services/product-service/go.mod services/product-service/go.sum ./
RUN go mod download

COPY services/product-service .
COPY pkg ./pkg

RUN CGO_ENABLED=0 GOOS=linux go build -o product-service ./cmd/main.go

RUN CGO_ENABLED=0 GOOS=linux go build -o product-service ./cmd/main.go


# Run Stage
FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/product-service .

EXPOSE 8082

CMD ["./product-service"]