# Build Stage
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY services/payment-service/go.mod services/payment-service/go.sum ./
RUN go mod download

COPY services/payment-service .
COPY pkg ./pkg

RUN CGO_ENABLED=0 GOOS=linux go build -o payment-service ./cmd/main.go

RUN CGO_ENABLED=0 GOOS=linux go build -o payment-service ./cmd/main.go


# Run Stage
FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/payment-service .

EXPOSE 8085

CMD ["./payment-service"]