# Build Stage
FROM golang:1.25-alpine AS builder

WORKDIR /src
COPY pkg ./pkg

WORKDIR /src/services/inventory-service
COPY services/inventory-service/go.mod services/inventory-service/go.sum ./
RUN go mod download

COPY services/inventory-service .

RUN CGO_ENABLED=0 GOOS=linux go build -o inventory-service ./cmd/main.go


# Run Stage
FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /src/services/inventory-service/inventory-service .

EXPOSE 8083

CMD ["./inventory-service"]