# Build Stage
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY services/inventory-service/go.mod services/inventory-service/go.sum ./
RUN go mod download

COPY services/inventory-service .
COPY pkg ./pkg

RUN CGO_ENABLED=0 GOOS=linux go build -o inventory-service ./cmd/main.go

RUN CGO_ENABLED=0 GOOS=linux go build -o inventory-service ./cmd/main.go


# Run Stage
FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/inventory-service .

EXPOSE 8083

CMD ["./inventory-service"]