apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: cartgo
type: Opaque
data:
  # Base64 encoded values
  user-db-url: cG9zdGdyZXM6Ly9hZG1pbnVzZXI6YWRtaW5wYXNzd29yZEBkYjpkYi1wb3J0L3VzZXJfZGI/c3NsbW9kZT1kaXNhYmxl
  product-db-url: cG9zdGdyZXM6Ly9hZG1pbnVzZXI6YWRtaW5wYXNzd29yZEBkYjpkYi1wb3J0L3Byb2R1Y3RfZGI/c3NsbW9kZT1kaXNhYmxl
  inventory-db-url: cG9zdGdyZXM6Ly9hZG1pbnVzZXI6YWRtaW5wYXNzd29yZEBkYjpkYi1wb3J0L2ludmVudG9yeV9kYj9zc2xtb2RlPWRpc2FibGU=
  order-db-url: cG9zdGdyZXM6Ly9hZG1pbnVzZXI6YWRtaW5wYXNzd29yZEBkYjpkYi1wb3J0L29yZGVyX2RiP3NzbG1vZGU9ZGlzYWJsZQ==
  payment-db-url: cG9zdGdyZXM6Ly9hZG1pbnVzZXI6YWRtaW5wYXNzd29yZEBkYjpkYi1wb3J0L3BheW1lbnRfZGI/c3NsbW9kZT1kaXNhYmxl
  delivery-db-url: cG9zdGdyZXM6Ly9hZG1pbnVzZXI6YWRtaW5wYXNzd29yZEBkYjpkYi1wb3J0L2RlbGl2ZXJ5X2RiP3NzbG1vZGU9ZGlzYWJsZQ==
  support-db-url: cG9zdGdyZXM6Ly9hZG1pbnVzZXI6YWRtaW5wYXNzd29yZEBkYjpkYi1wb3J0L3N1cHBvcnRfZGI/c3NsbW9kZT1kaXNhYmxl
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: cartgo
type: Opaque
data:
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQta2V5
