# Build Stage
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY services/delivery-service/go.mod services/delivery-service/go.sum ./
RUN go mod download

COPY services/delivery-service .
COPY pkg ./pkg

RUN CGO_ENABLED=0 GOOS=linux go build -o delivery-service ./cmd/main.go

RUN CGO_ENABLED=0 GOOS=linux go build -o delivery-service ./cmd/main.go


# Run Stage
FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/delivery-service .

EXPOSE 8086

CMD ["./delivery-service"]