# Build Stage
FROM golang:1.25-alpine AS builder

WORKDIR /src
COPY pkg ./pkg

WORKDIR /src/services/delivery-service
COPY services/delivery-service/go.mod services/delivery-service/go.sum ./
RUN go mod download

COPY services/delivery-service .

RUN CGO_ENABLED=0 GOOS=linux go build -o delivery-service ./cmd/main.go


# Run Stage
FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /src/services/delivery-service/delivery-service .

EXPOSE 8086

CMD ["./delivery-service"]