# Build Stage
FROM golang:1.25-alpine AS builder

WORKDIR /src
COPY pkg ./pkg

WORKDIR /src/services/user-service
COPY services/user-service/go.mod services/user-service/go.sum ./
RUN go mod download

COPY services/user-service .

RUN CGO_ENABLED=0 GOOS=linux go build -o user-service ./cmd/main.go


# Run Stage
FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /src/services/user-service/user-service .

EXPOSE 8081

CMD ["./user-service"]