/**
 * Deterministic Lifecycle States
 */
export const SYSTEM_STATES = {
  CREATED: "CREATED",
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  RESOLVING_ORDER_CONFIRMATION: "RESOLVING_ORDER_CONFIRMATION", // P -> SUCCESS, O -> PENDING
  CONFIRMED: "CONFIRMED",
  INVENTORY_RESERVED: "INVENTORY_RESERVED",
  RESOLVING_DELIVERY_ASSIGNMENT: "RESOLVING_DELIVERY_ASSIGNMENT", // O -> CONFIRMED, D -> NONE
  DELIVERY_ASSIGNED: "DELIVERY_ASSIGNED",
  PICKED_UP: "PICKED_UP",
  IN_TRANSIT: "IN_TRANSIT",
  DELIVERED: "DELIVERED",
  INCONSISTENT: "INCONSISTENT",
};

/**
 * Service Responsibility Mapping
 */
export const SERVICE_OWNERSHIP = {
  [SYSTEM_STATES.CREATED]: "Order Service",
  [SYSTEM_STATES.PAYMENT_PENDING]: "Payment Service",
  [SYSTEM_STATES.PAYMENT_SUCCESS]: "Payment Service",
  [SYSTEM_STATES.PAYMENT_FAILED]: "Payment Service",
  [SYSTEM_STATES.RESOLVING_ORDER_CONFIRMATION]: "System Orchestrator",
  [SYSTEM_STATES.CONFIRMED]: "Order Service",
  [SYSTEM_STATES.INVENTORY_RESERVED]: "Warehouse (Inventory)",
  [SYSTEM_STATES.RESOLVING_DELIVERY_ASSIGNMENT]: "System Orchestrator",
  [SYSTEM_STATES.DELIVERY_ASSIGNED]: "Delivery Service",
  [SYSTEM_STATES.PICKED_UP]: "Delivery Partner",
  [SYSTEM_STATES.IN_TRANSIT]: "Delivery Partner",
  [SYSTEM_STATES.DELIVERED]: "System Lifecycle Complete",
};

/**
 * Valid Transitions (State Machine)
 */
export const VALID_TRANSITIONS = {
  [SYSTEM_STATES.CREATED]: [SYSTEM_STATES.PAYMENT_PENDING],
  [SYSTEM_STATES.PAYMENT_PENDING]: [SYSTEM_STATES.PAYMENT_SUCCESS, SYSTEM_STATES.PAYMENT_FAILED],
  [SYSTEM_STATES.PAYMENT_SUCCESS]: [SYSTEM_STATES.RESOLVING_ORDER_CONFIRMATION, SYSTEM_STATES.CONFIRMED],
  [SYSTEM_STATES.RESOLVING_ORDER_CONFIRMATION]: [SYSTEM_STATES.CONFIRMED],
  [SYSTEM_STATES.CONFIRMED]: [SYSTEM_STATES.INVENTORY_RESERVED],
  [SYSTEM_STATES.INVENTORY_RESERVED]: [SYSTEM_STATES.RESOLVING_DELIVERY_ASSIGNMENT, SYSTEM_STATES.DELIVERY_ASSIGNED],
  [SYSTEM_STATES.RESOLVING_DELIVERY_ASSIGNMENT]: [SYSTEM_STATES.DELIVERY_ASSIGNED],
  [SYSTEM_STATES.DELIVERY_ASSIGNED]: [SYSTEM_STATES.PICKED_UP],
  [SYSTEM_STATES.PICKED_UP]: [SYSTEM_STATES.IN_TRANSIT],
  [SYSTEM_STATES.IN_TRANSIT]: [SYSTEM_STATES.DELIVERED],
  [SYSTEM_STATES.DELIVERED]: [], // Terminal
};

/**
 * System Invariants
 */
export const SYSTEM_INVARIANTS = [
  {
    name: "Success Payment => Confirmed Order",
    rule: (state, derivedState) => {
       // Suppress check while system is actively resolving the drift
       if (derivedState === "RESOLVING_ORDER_CONFIRMATION") return true;
       if (state.payment?.status === "SUCCESS" && state.order?.status === "FAILED") return false;
       return true;
    },
    errorCode: "ORDER_PAYMENT_MISMATCH"
  },
  {
    name: "Delivered => Success Payment",
    rule: (state) => {
       if (state.delivery?.status === "DELIVERED" && state.payment?.status !== "SUCCESS") return false;
       return true;
    },
    errorCode: "DELIVERY_PAYMENT_INCONSISTENCY"
  }
];
