# Build Stage
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY services/order-service/go.mod services/order-service/go.sum ./
RUN go mod download

COPY services/order-service .
COPY pkg ./pkg

RUN CGO_ENABLED=0 GOOS=linux go build -o order-service ./cmd/main.go

RUN CGO_ENABLED=0 GOOS=linux go build -o order-service ./cmd/main.go


# Run Stage
FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/order-service .

EXPOSE 8084

CMD ["./order-service"]